# Generated by Django 5.2.17 on 2026-09-17 12:18

import corporate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms_hub', '0003_attach_real_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmupdate',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_updates/', validators=[corporate.validators.validate_image_upload]),
        ),
    ]
