# Generated by Django 5.2.17 on 2026-10-04 10:49

import corporate.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms_hub', '0007_finalize_category_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_photos/', validators=[corporate.validators.validate_image_upload])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='farms_hub.farmupdate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
