# Generated by Django 5.2.17 on 2026-09-17 12:18

import corporate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_seed_real_faq_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', validators=[corporate.validators.validate_image_upload]),
        ),
    ]
