# Generated by Django 5.2.17 on 2026-09-21 06:39

import corporate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mission', 'Our mission — focus areas'), ('different', 'What makes us different')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('subhead', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InsightPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_label', models.CharField(blank=True, help_text='e.g. Report, Guide, Trends', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('date_label', models.CharField(blank=True, help_text='e.g. 2025', max_length=40)),
                ('file', models.FileField(blank=True, help_text='Optional PDF or document for readers to download.', null=True, upload_to='thrivepoint/', validators=[corporate.validators.validate_document_upload])),
                ('external_url', models.URLField(blank=True, help_text='Optional link instead of, or alongside, a file.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('page', models.CharField(blank=True, choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('thrivepoint', 'ThrivePoint Insights'), ('faq', 'FAQ'), ('contact', 'Contact')], help_text='Pick a page on this site — or leave blank and fill in an external link below (for Media, Farms, Homes, or anywhere off this site).', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text="Used only when 'page' above is left blank.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Nairobi HQ', max_length=80)),
                ('address', models.TextField()),
                ('maps_url', models.URLField(blank=True, help_text='Optional Google Maps link.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('thrivepoint', 'ThrivePoint Insights'), ('faq', 'FAQ'), ('contact', 'Contact'), ('media_list', 'Media — list page'), ('farms_list', 'Farms — list page')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, help_text='Browser tab title. Leave blank to use the default.', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Search engine snippet. Leave blank to use the default.', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('link_label', models.CharField(blank=True, default='Learn more →', max_length=60)),
                ('link_url', models.CharField(blank=True, help_text='A full link (https://...) or a path on this site (e.g. /contact/). Leave blank to hide the link.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='+254705837629', help_text='Include the country code, no spaces or dashes, e.g. +254705837629.', max_length=32)),
                ('whatsapp_message', models.CharField(blank=True, default='Hello I would like to connect', help_text='Pre-filled message when someone taps the WhatsApp button.', max_length=255)),
                ('contact_email', models.EmailField(default='Admin@afraviva.com', max_length=254)),
                ('contact_phone_lines', models.TextField(default='Kenya: +254 705 837629\nUganda: +256 392 964978', help_text='One phone line per row, e.g. "Kenya: +254 700 000000".')),
                ('footer_blurb', models.TextField(default='Media, Homes and Farms — brands of AfricaNext Opportunities (ANO), building sustainable, purpose-driven businesses across Africa.')),
                ('copyright_text', models.CharField(default='AfraViva, a brand of AfricaNext Opportunities. All rights reserved. · Site developed by Jude Kioko', help_text='Shown after the year in the footer, e.g. "(c) 2026 {this text}".', max_length=255)),
                ('homes_url', models.URLField(default='https://homes.afraviva.com')),
                ('media_url', models.URLField(default='https://media.afraviva.com')),
                ('farms_url', models.URLField(default='https://farms.afraviva.com')),
                ('home_intro_heading', models.CharField(default="Building Africa's Future with Purpose and Impact", max_length=200)),
                ('home_intro_body', models.TextField(default='At AfraViva, the brand of AfricaNext Opportunities (ANO), we blend talent and ambition to grow impactful businesses across Africa. Rooted in Christian values of justice and community, we accelerate startups and invest in sectors that uplift lives — delivering sustainability and success.')),
                ('home_media_partner_name', models.CharField(blank=True, default='LifeSiteNews', max_length=120)),
                ('home_media_partner_description', models.TextField(blank=True, default='Internet news service established in Canada in 1997, now active worldwide, dedicated to issues of life, family, and faith.')),
                ('vision_eyebrow', models.CharField(blank=True, default='AfricaNext Vision, Guiding Principles & Objectives', max_length=200)),
                ('vision_heading', models.CharField(blank=True, default='Crafting a future of innovation and impact', max_length=200)),
                ('vision_fun_fact', models.TextField(blank=True, default='AfricaNext\'s vision is guided by time-tested Christian values as elucidated in sacred scripture, as well as classic Church social teachings such as Pope Leo XIII\'s "Of New Things" (Rerum Novarum, 1891) and Pope John Paul II\'s "Through Work" (Laborem Exercens, 1981).')),
                ('services_intro', models.TextField(blank=True, default='Discover how we empower your goals with innovative expertise.')),
                ('thrivepoint_intro', models.TextField(blank=True, default='Full report content and downloads will be added once migrated from the current site.')),
                ('about_hero_heading', models.CharField(blank=True, default='We are committed to excellence', max_length=200)),
                ('about_hero_body', models.TextField(blank=True, default='We believe in the power of sustainable practices, spiritual values and cultural richness to create a brighter future for Africa.')),
                ('about_overview', models.TextField(blank=True, default="We work with ambitious clients across Africa who want to define the future, not hide from it.\n\nOur firm delivers innovative solutions in Agribusiness, Digital Media Production, Estate Development Consultancy, and Business Development. We partner with individuals, organizations and institutions to drive progress, spark growth, and unlock new opportunities across diverse sectors and communities.\n\nWe measure our success by the positive impact we create: empowering farmers and agribusinesses, crafting compelling digital content, guiding estate investments with expert insight, and building sustainable businesses that thrive in today's competitive landscape.", help_text='Separate paragraphs with a blank line.')),
                ('about_mission', models.TextField(blank=True, default="We craft transformative, client-centric solutions to reshape industries and enrich lives. Guided by integrity, innovation, and an intimate knowledge of Africa's vibrant landscape, we forge a path to a thriving, prosperous future.")),
                ('about_footnote', models.TextField(blank=True, default='AfraViva is the operating brand of AfricaNext Opportunities (ANO), guided by time-tested Christian values of justice and community.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Facebook, Instagram, YouTube', max_length=40)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisionPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
