# Generated by Django 5.2.17 on 2026-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0006_farms_seo_uganda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='media_url',
            field=models.URLField(default='https://afravivamedia.com'),
        ),
    ]
