# Generated by Django 5.2.17 on 2026-09-17 12:18

import corporate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_hub', '0005_pro_family_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media_posts/', validators=[corporate.validators.validate_image_upload]),
        ),
    ]
