# Generated by Django 5.2.17 on 2026-09-21 06:39

import corporate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_hub', '0006_alter_mediapost_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly (under 200MB). Leave blank if using a YouTube/Vimeo link instead.', null=True, upload_to='media_videos/', validators=[corporate.validators.validate_video_upload]),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='video_url',
            field=models.URLField(blank=True, help_text='A YouTube or Vimeo link to embed. Leave blank if uploading a video file below instead.'),
        ),
    ]
