# Generated by Django 5.2.17 on 2026-10-08 09:07

import media_hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_hub', '0008_mediavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Link to one TikTok video.', validators=[media_hub.models.validate_tiktok_video_url])),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Featured TikTok video',
                'ordering': ['order', 'id'],
            },
        ),
    ]
